controller_manager:
  ros__parameters:
    update_rate: 100 #Hz
    Propuesta2_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      # Note: Unlike forward_command_controller/ForwardCommandController
      # with joint_trajectory_controller/JointTrajectoryController, the joint position is not instantaneously reached
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
 
Propuesta2_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      #- effort
    joints:
      - base_link_to_link_1
      - link_1_to_link_2
      - link_2_to_link_3
      - link_3_to_link_4
      - link_P_joint

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03