controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    scara_position_controller: #-------
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

scara_position_controller: #---------
  ros__parameters:
    joints:
      - link_1_joint
      - link_2_joint
      - link_3_joint
    interface_name: position